name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        VITE_GITHUB_TOKEN: ${{ secrets.PERSONAL_WEBSITE }}
        
    - name: Deploy
      uses: andre-moura/https://github.com/andre-moura/personal-website/tree/gh-pages
      with:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_WEBSITE }}
        BRANCH: gh-pages
        FOLDER: build
